### ISSUE TITLE
Is this being maintained?

### ISSUE THREAD

**Issue by bitemyapp** [dgvncsz0f/hzk#2]
Please let us know. :)

**Comment by dgvncsz0f** [comment]
I've been using it sucessfully for a while now. That said, I have no roadmap for it but bug fixing.

Is there anything you need or miss?

**Comment by bitemyapp** [comment]
@dgvncsz0f just wanted some assurance it was being maintained so we can use it for a Kafka client. Does it work with the current version of Zookeeper?

**Comment by junjihashimoto** [comment]
hzk works on zookeeper-3.4.5. 
I want "Data.Pool's IF" or "open & close-function"
for http://hackage.haskell.org/package/persistent-zookeeper-0.0.3.
No these function causes dirty-code like below. "https://github.com/junjihashimoto/persistent/blob/master/persistent-zookeeper/Database/Persist/Zookeeper/ZooUtil.hs".

**Comment by dgvncsz0f** [comment]
I can't dedicate much more than a couple of hours per week to work on this, but yes, I will maintain it if there is somthing that comes up.

**Comment by dgvncsz0f** [comment]
@junjihashimoto I'll review your patch tonight or the day after and I'll let you know! Thx
